openapi: 3.1.0
info:
  title: Physical AI Platform - Authentication API
  description: JWT-based authentication with bcrypt password hashing
  version: 1.0.0

servers:
  - url: http://localhost:8000
  - url: https://api.physicalai.edu

paths:
  /api/auth/sign-up:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 100
      responses:
        '201':
          description: User created
          headers:
            Set-Cookie:
              schema:
                type: string
              description: HTTP-only JWT cookie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Email already registered

  /api/auth/sign-in:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Invalid credentials
        '429':
          description: Rate limit (5 failed/15min)

  /api/auth/sign-out:
    post:
      summary: Logout
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logged out

  /api/auth/me:
    get:
      summary: Get current user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

components:
  schemas:
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_at:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/UserResponse'

    UserResponse:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        created_at:
          type: string
          format: date-time

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
